services:
  postgres:
    image: postgres:17-alpine
    ports:
      - 5432:5432
    env_file:
      - .env.development
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512MB"
